/* Copyright 2026 上海如静知华信息科技有限公司 · https://www.zhuatech.cn/ */
export const domain={
 code:'AIFINOPS',systemName:'知华 AI FinOps',englishName:'AI COST & VALUE OPERATIONS',theme:{primary:'#276a8c',dark:'#203541',accent:'#2e9773'},workspace:'技术平台中心 / AI 成本运营',fieldWorkspace:'AI 平台成本组',period:'2026-08 · 月度账期',liveText:'成本账本于 10:38 更新',fieldContextLabel:'当前成本域',fieldContext:'生产环境 · 全业务',fieldUser:'陆遥',fieldRole:'AI 成本分析师',adminUser:'何谨',adminRole:'FinOps 负责人',adminTitle:'AI 成本与业务价值驾驶舱',adminBreadcrumb:'AI FinOps / 成本总览',adminSubtitle:'归集模型 API、GPU 与向量服务成本，关联项目预算和业务成果，推动持续优化。',exportAction:'导出成本月报',createAction:'新建优化任务',chartTitle:'AI 成本与预算趋势',chartSubtitle:'累计实际支出 / 月度预算基线',chartLabels:['01日','05日','09日','13日','17日','21日','25日','29日','31日'],loadTitle:'成本中心预算消耗',loadSubtitle:'当前支出占月度预算',recordsTitle:'重点成本优化任务',recordsSubtitle:'按预算偏差、节省潜力与业务影响排序',issueTitle:'成本异常与预算风险',issueSubtitle:'需要平台和业务负责人共同处理的项目',recordName:'优化任务',itemName:'AI 场景',unitName:'责任团队',batchName:'月度预算',planName:'优化项',doneName:'已完成',exceptionName:'异常项',unitLabel:'项',
 listBreadcrumb:'成本运营 / 优化任务',listSubtitle:'管理账单归集、成本分摊、预算预警、异常归因和优化收益验证。',listSummary:[['本月支出','¥486K'],['预算执行','72.4%'],['确认节省','¥83K'],['超支项目','3',true]],tabs:['全部','待归因','优化中','待验证','已结案'],fieldBreadcrumb:'AI FinOps / 分析师工作台',fieldTitle:'AI 成本分析工作台',fieldSubtitle:'当前 6 个优化任务 · 3 个预算风险 · 分析师陆遥',fieldSecondary:'查看账单日历',reportAction:'提交优化结果',fieldNoticeTitle:'多云账单采集链路正常',fieldNotice:'模型 API、GPU 和向量服务标签覆盖率 96.2%',steps:['账单归集','成本分摊','异常识别','优化实施','收益验证'],documentAction:'查看核算口径',printAction:'导出成本明细',resourceCardTitle:'成本数据源状态',resourceValueLabel:'已归集账单',resourceHealthLabel:'标签覆盖率',quickSubtitle:'成本分析师常用入口',quickActions:[['优化反馈','/shopfloor/report','措施、节省与效果验证'],['成本账本','/shopfloor/material','提供商、模型与项目明细'],['资源利用率','/shopfloor/resources','GPU、缓存和批处理状态'],['预算升级','/shopfloor/andon','超支、突增和归集异常']],reportDefaults:[6,1],reportTitle:'成本优化结果',reportSubtitle:'记录已完成措施、异常项和确认节省。',reportSuccess:'优化结果已写入成本账本',reportPlaceholder:'填写成本基线、优化措施、节省金额与业务影响',reportFootnote:'收益需经过完整账期验证后计入确认节省',ruleTitle:'AI 成本治理基线',ruleSubtitle:'AI-FINOPS · V1.6',rules:[['项目标签覆盖','≥ 95%'],['预算告警阈值','80%'],['异常波动','> 20%'],['收益验证','完整账期',true]],fieldTotals:[['¥486K','本月 AI 支出'],['72.4%','预算执行率'],['¥83K','确认节省'],['96.2%','标签覆盖率']],
 adminMenus:[['/admin','home','成本驾驶舱'],['/admin/work-orders','order','优化任务'],['/admin/samples','box','成本账本'],['/admin/schedule','calendar','预算计划'],['/admin/methods','process','分摊规则'],['/admin/reviews','quality','收益验证'],['/admin/resources','machine','资源利用率'],['/admin/report','chart','单位经济性']],fieldMenus:[['/shopfloor','home','分析师工作台'],['/shopfloor/report','report','优化反馈'],['/shopfloor/tasks','order','我的任务'],['/shopfloor/material','box','成本账本'],['/shopfloor/resources','machine','资源状态'],['/shopfloor/andon','risk','预算升级',3]],moduleTitles:{tasks:['我的优化任务','查看预算偏差、节省目标与验证期限'],material:['AI 成本账本','查询提供商、模型、Token、GPU 与项目分摊'],resources:['资源利用率','查看 GPU、缓存、批处理和推理端点效率'],andon:['预算升级','提交超支、成本突增和账单归集异常'],samples:['成本账本','统一归集模型 API、算力和向量服务成本'],schedule:['预算计划','编制成本中心预算和滚动预测'],methods:['分摊规则','维护标签、共享成本和业务成果口径'],reviews:['收益验证','验证节省金额、质量和业务指标'],report:['单位经济性','分析每次对话、文档和业务成果成本']},tagline:'看清每一笔 AI 成本，也看见它创造的价值',storyTitle:'不只控制账单，<br/>更要经营 AI 的单位经济性。',storyText:'将模型调用、算力资源、项目预算和业务成果串成可行动的成本运营闭环。',pattern:[1,4,6,9,12,15,18,21,24,27,30,32],loginStats:[['¥486K','本月 AI 支出'],['¥83K','确认节省'],['96.2%','标签覆盖率']],loginTitle:'AI 成本与业务价值驾驶舱',adminDemo:'成本 / 预算 / 价值',fieldDemo:'归集 / 优化 / 验证'
}
export const records=[{no:'COST-260801-018',name:'客服助手推理成本优化',code:'CS-COPILOT',unit:'AI 平台成本组',group:'技术平台中心',plan:24,done:16,exception:2,due:'08-05',batch:'¥240K',status:'优化中',progress:67,priority:'加急'},{no:'COST-260801-021',name:'票据识别 GPU 批处理优化',code:'DOC-OCR',unit:'算力运营组',group:'云基础设施部',plan:18,done:8,exception:1,due:'08-06',batch:'¥120K',status:'实施中',progress:48,priority:'关注'},{no:'COST-260802-006',name:'销售 Agent 单位成果核算',code:'SALES-AGENT',unit:'业务价值分析组',group:'数字化办公室',plan:12,done:0,exception:0,due:'08-08',batch:'¥80K',status:'待归因',progress:15,priority:'正常'},{no:'COST-260728-015',name:'知识检索缓存策略复盘',code:'SEARCH-RAG',unit:'AI 平台成本组',group:'技术平台中心',plan:20,done:20,exception:1,due:'08-01',batch:'¥65K',status:'已结案',progress:100,priority:'正常'},{no:'COST-260802-009',name:'多模型路由质量成本校准',code:'MODEL-ROUTER',unit:'AI 平台成本组',group:'技术平台中心',plan:16,done:11,exception:3,due:'08-07',batch:'¥96K',status:'待验证',progress:73,priority:'关注'}]
export const resources=[{code:'COST-MODEL-03',name:'模型 API 账单采集',unit:'技术平台中心',status:'正常',health:98,value:'¥312K',valueUnit:'',note:'覆盖 6 家模型服务商'},{code:'COST-GPU-02',name:'GPU 利用率采集',unit:'云基础设施部',status:'正常',health:91,value:'68%',valueUnit:'',note:'离线任务平均利用率'},{code:'COST-TAG-05',name:'项目标签覆盖',unit:'数字化办公室',status:'预警',health:76,value:'96.2%',valueUnit:'',note:'3 个共享服务待拆分'}]
export const reviews=[{no:'SAVE-260801-032',title:'客服助手模型路由节省验证',type:'收益确认',detail:'预计 ¥36K/月 · 何谨',result:'待确认'},{no:'SAVE-260801-011',title:'OCR GPU 批处理效果验证',type:'资源优化',detail:'利用率 +21% · 陆遥',result:'通过'},{no:'SAVE-260728-018',title:'共享向量库成本分摊复核',type:'归集质量',detail:'差异 ¥8.4K',result:'异常'}]
export const adminMetrics=[['本月 AI 支出','¥486K','预算执行 72.4%','blue'],['确认节省','¥83K','年度化 ¥996K','green'],['待归因成本','¥27K','占总支出 5.6%','orange'],['超支项目','3','最大偏差 18.7%','red']]
export const fieldMetrics=[['我的优化任务','6','潜在节省 ¥51K','blue'],['本周已验证','¥18K','2 项收益确认','green'],['待归因账单','7','金额 ¥27K','orange'],['标签覆盖率','96.2%','目标 98%','slate']]
export const chartActual=[12,19,28,36,45,53,61,67,72],chartTarget=[11,18,27,35,44,52,60,68,76]
export const loads=[['客服与营销 AI',84,'预算 ¥240K'],['文档智能处理',76,'预算 ¥160K'],['研发与知识助手',63,'预算 ¥120K'],['Agent 自动化',57,'预算 ¥96K']]
export const issues=[{type:'突增',title:'客服助手输出 Token 连续三日增长',detail:'较基线高 24% · 预计多支出 ¥18K',status:'分析中'},{type:'预算',title:'票据识别 GPU 预算执行达到 86%',detail:'月底预测超支 11.2%',status:'优化中'},{type:'归集',title:'共享向量库缺少业务项目标签',detail:'待分摊成本 ¥8.4K',status:'待处理'}]
